CREATE SEQUENCE user_seq START WITH 2 INCREMENT BY 1 MINVALUE 1;
create table HORTICOLA._USER (
    ID_USER    BIGINT NOT NULL PRIMARY KEY,
    CPF        CHARACTER VARYING(11) UNIQUE,
    EMAIL      CHARACTER VARYING(60),
    FIRST_NAME CHARACTER VARYING(20),
    LAST_NAME  CHARACTER VARYING(100),
    PASSWORD   CHARACTER VARYING(255)
);
INSERT INTO HORTICOLA._USER (ID_USER, CPF, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD) VALUES (1, '06226766107', 'kelvin@gmail.com', 'KELVIN', 'PEREIRA BISERRA', '$2a$10$ts98GgDiTqfw3Mz9QLFz0.3NoSmx6rppRNSARZphUqP1TgpiL90C.');


CREATE SEQUENCE perfil_seq START WITH 2 INCREMENT BY 1 MINVALUE 1;
create table HORTICOLA._PERFIL (
    ID_PERFIL   BIGINT NOT NULL PRIMARY KEY,
    PERFIL      CHARACTER VARYING(255),
    ID_USER     BIGINT,
    FOREIGN KEY (ID_USER) REFERENCES HORTICOLA._USER(ID_USER)
);
INSERT INTO HORTICOLA._PERFIL (ID_PERFIL, PERFIL, ID_USER) VALUES (1, 'ADMIN', 1);

// TODO fazer inser usando .nextValue